name: Deploy to GitHub Pages

on:
 push:
   branches: [ main ]

env:
 PUBLIC_EMAILJS_KEY: ${{ secrets.PUBLIC_EMAILJS_KEY }}
 PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.PUBLIC_EMAILJS_SERVICE_ID }}
 PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.PUBLIC_EMAILJS_TEMPLATE_ID }}
 PUBLIC_TURNSTILE_KEY: ${{ secrets.PUBLIC_TURNSTILE_KEY }}

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '18'
     - name: Install dependencies
       run: npm ci
     - name: Build
       run: npm run build
       env:
         PUBLIC_EMAILJS_KEY: ${{ secrets.PUBLIC_EMAILJS_KEY }}
         PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.PUBLIC_EMAILJS_SERVICE_ID }}
         PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.PUBLIC_EMAILJS_TEMPLATE_ID }}
         PUBLIC_TURNSTILE_KEY: ${{ secrets.PUBLIC_TURNSTILE_KEY }}
     - name: Create .nojekyll
       run: touch dist/.nojekyll
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.MONTOKENCUL }}
         publish_dir: ./dist